[package]
name = "trs2midi_usb_expression_pedal"
version = "0.1.0"
edition = "2024"


[dependencies]
embassy-executor = { version = "0.9", features = [ "arch-cortex-m", "executor-thread", "defmt", ] }

embassy-time = { version = "0.5", features = [ "defmt", "defmt-timestamp-uptime", "tick-hz-1_000_000", ] }

embassy-rp = { version = "0.9", features = [ "defmt", "unstable-pac", "time-driver", "critical-section-impl", "rp235xa", ] }

embassy-usb = { version = "0.5.1", features = [ "defmt", ] }

static_cell = "2"

defmt = "1"
defmt-rtt = "1"
panic-probe = { version = "1", features = ["print-defmt"] }

cortex-m = "0.7"
cortex-m-rt = "0.7"